run_name: pions_ep50_testrepro_42everywhere
p_type: piplus
dtype: float32
# Data
data_path: /gpfs/users/maiborodav/itwinai/use-cases/caloinn/calochallenge_data/dataset_1_pions_1_train.hdf5 #/gpfs/users/maiborodav/CaloINN/data/ds1-pions/caloINN_sample.hdf5
val_data_path: /gpfs/users/maiborodav/itwinai/use-cases/caloinn/calochallenge_data/dataset_1_pions_2_test.hdf5 #/gpfs/users/maiborodav/CaloINN/data/ds1-pions/caloINN_sample.hdf5
xml_path: /gpfs/users/maiborodav/CaloINN/binning_dataset_1_pions.xml
single_energy: null
width_noise: 5.0e-6
custom_noise: False
fixed_noise: False
noise: True
val_frac: 0.01
eps: 1.0e-10
xml_ptype: "pion"
eval_dataset: "1-pions"
u0up_cut: 3.5
u0low_cut: 0.0
pt_rew: 1.0
dep_cut: 600

# Training
lr: 1.e-5
max_lr: 1.e-4
batch_size: 512

lr_scheduler: one_cycle_lr

weight_decay: 0.01
betas: [0.9, 0.999]
n_epochs: 1
cycle_epochs: 37
save_interval: 50

# Architecture
n_blocks: 12
internal_size: 256
layers_per_block: 4
coupling_type: rational_quadratic
bounds_init: 18
permute_soft: False
permute_layer: False
num_bins: 10
dropout: 0.0
layer_norm: nn.BatchNorm1d
layer_act: nn.SiLU
bayesian: False
prior_prec: 5000
std_init: -15.0

sub_layers: [linear, linear, linear, linear]
norm: True
# Preprocessing
use_extra_dims: True
use_norm: False
log_cond: True
alpha: 1.0e-8
alpha_logit: 1.0e-6
