run_name: pions_new_class_17epohc        # nom du folder qui va save les resultats
p_type: piplus               # particle type, type de dataset , pion, e...
dtype: float32               # precision numérique qu'on veut avoir (32 bits)
# Data
data_path: /pbs/home/z/zriche/CaloINN/data/dataset_1_pions_1.hdf5
val_data_path: /pbs/home/z/zriche/CaloINN/data/dataset_1_pions_2.hdf5        #testing set
xml_path: /pbs/home/z/zriche/CaloINN/binning_dataset_1_pions.xml        #binning file
single_energy: null         # si on veut sélectionner une énergie incidente en particulier
width_noise: 5.0e-6
custom_noise: False
fixed_noise: False
noise: True
val_frac: 0.01
eps: 1.0e-10             # évite les divisions par 0, ajt des petites valeurs au dénominateur
xml_ptype: "pion"        # préciser la particule
eval_dataset: "1-pions"
u0up_cut: 3.5
u0low_cut: 0.0
pt_rew: 1.0
dep_cut: 600

# Training
lr: 1.e-5                   # c'est le lr DE DÉPART
max_lr: 1.e-4               # c'est la valeur max du lr pendant un cycle
batch_size: 512           

lr_scheduler: one_cycle_lr

weight_decay: 0.01         # régularisation, pénalise les grands poids pour éviter overfitting
betas: [0.9, 0.999]        # param internes de Adam, controlent la mémoire de l'optimiseur
n_epochs: 17
cycle_epochs: 37
save_interval: 50

# Architecture
n_blocks: 12
internal_size: 256
layers_per_block: 4
coupling_type: rational_quadratic
bounds_init: 18
permute_soft: False
permute_layer: False
num_bins: 10
dropout: 0.0
layer_norm: nn.BatchNorm1d
layer_act: nn.SiLU
bayesian: False
prior_prec: 5000
std_init: -15.0

sub_layers: [linear, linear, linear, linear]
norm: True
# Preprocessing
use_extra_dims: True
use_norm: False
log_cond: True
alpha: 1.0e-8
alpha_logit: 1.0e-6
